name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Mỗi lần push main thì workflow chạy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Cài Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.150.0" # thay bằng version Hugo bạn dùng

      # 3. Build website
      - name: Build
        run: hugo --minify

      # 4. Deploy lên GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
